# Generated by Django 3.0.8 on 2020-10-17 06:14

import clubs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAccount',
            fields=[
                ('club_name', models.CharField(default='', max_length=1000, primary_key=True, serialize=False)),
                ('club_website', models.URLField(null=True)),
                ('ig_url', models.URLField(null=True)),
                ('club_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('club_logo', models.ImageField(default='', null=True, upload_to=clubs.models.path_and_rename_logos)),
            ],
        ),
        migrations.CreateModel(
            name='BigRecruitment',
            fields=[
                ('club_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clubs.ClubAccount')),
                ('rec_date_time', models.DateTimeField(null=True)),
                ('rec_desc', models.TextField(default='', max_length=1000, null=True)),
                ('poster', models.ImageField(default='', null=True, upload_to=clubs.models.path_and_rename_recs)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('club_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clubs.ClubAccount')),
                ('rec_date_time', models.DateTimeField(null=True)),
                ('rec_desc', models.TextField(default='', max_length=1000, null=True)),
                ('recruit_poster', models.ImageField(default='', null=True, upload_to=clubs.models.path_and_rename_recs)),
            ],
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('event_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('event_desc', models.TextField(default='', max_length=1000, null=True)),
                ('event_poster', models.ImageField(default='', null=True, upload_to=clubs.models.path_and_rename_events)),
                ('event_url', models.URLField(default='', null=True)),
                ('club_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ClubBigEvent',
            fields=[
                ('event_name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('event_desc', models.TextField(default='', max_length=1000, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to=clubs.models.path_and_rename_events)),
                ('event_url', models.URLField(default='', null=True)),
                ('club_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.ClubAccount')),
            ],
        ),
    ]
