# Generated by Django 3.0.8 on 2020-10-25 10:14

import clubs.models
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigrecruitment',
            name='poster',
            field=models.ImageField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=clubs.models.path_and_rename_recs),
        ),
        migrations.AlterField(
            model_name='clubaccount',
            name='club_logo',
            field=models.ImageField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=clubs.models.path_and_rename_logos),
        ),
        migrations.AlterField(
            model_name='clubbigevent',
            name='image',
            field=models.ImageField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=clubs.models.path_and_rename_events),
        ),
        migrations.AlterField(
            model_name='clubevent',
            name='event_poster',
            field=models.ImageField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=clubs.models.path_and_rename_events),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='recruit_poster',
            field=models.ImageField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=clubs.models.path_and_rename_recs),
        ),
    ]
