# Generated by Django 3.0.8 on 2020-10-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20201025_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigrecruitment',
            name='urlfield',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='clubaccount',
            name='imgurl',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='clubbigevent',
            name='urlfield',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='imgurl',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='urlfield',
            field=models.URLField(default='', null=True),
        ),
    ]
