# Generated by Django 3.0.8 on 2020-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20201025_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='urlfield',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
