# Generated by Django 3.0.8 on 2020-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20201025_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigrecruitment',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='clubaccount',
            name='imgurl',
        ),
        migrations.RemoveField(
            model_name='clubbigevent',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='clubevent',
            name='imgurl',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='urlfield',
        ),
        migrations.AddField(
            model_name='bigrecruitment',
            name='poster_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clubaccount',
            name='logo_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clubbigevent',
            name='img_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clubevent',
            name='poster_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='poster_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
