# Generated by Django 3.0.8 on 2020-10-17 06:14

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAT1',
            fields=[
                ('course_code', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=200, null=True)),
                ('cat_1', models.FileField(default='', null=True, upload_to=resources.models.path_and_rename_cat1)),
            ],
            options={
                'verbose_name': 'CAT 1 Paper',
                'verbose_name_plural': 'CAT 1 papers',
            },
        ),
        migrations.CreateModel(
            name='CAT2',
            fields=[
                ('course_code', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=200, null=True)),
                ('cat_2', models.FileField(default='', null=True, upload_to=resources.models.path_and_rename_cat2)),
            ],
            options={
                'verbose_name': 'CAT 2 Paper',
                'verbose_name_plural': 'CAT 2 papers',
            },
        ),
        migrations.CreateModel(
            name='FAT',
            fields=[
                ('course_code', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=200, null=True)),
                ('fat_paper', models.FileField(default='', null=True, upload_to=resources.models.path_and_rename_fat)),
            ],
            options={
                'verbose_name': 'FAT Paper',
                'verbose_name_plural': 'FAT Papers',
            },
        ),
    ]
