# Generated by Django 3.0.8 on 2020-10-22 17:02

from django.db import migrations, models
import gdstorage.storage
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat1files',
            name='cat_1',
            field=models.FileField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=resources.models.path_and_rename_cat1),
        ),
        migrations.AlterField(
            model_name='cat2files',
            name='cat_2',
            field=models.FileField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=resources.models.path_and_rename_cat2),
        ),
        migrations.AlterField(
            model_name='fatfiles',
            name='fat_paper',
            field=models.FileField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=resources.models.path_and_rename_fat),
        ),
    ]
