# Generated by Django 3.0.8 on 2020-10-22 17:19

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201022_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat1files',
            name='cat_1',
            field=models.FileField(default='', null=True, upload_to=resources.models.path_and_rename_cat1),
        ),
    ]
