# Generated by Django 3.0.8 on 2020-10-25 10:14

from django.db import migrations, models
import gdstorage.storage
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20201022_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat1files',
            name='cat_1',
            field=models.FileField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=resources.models.path_and_rename_cat1),
        ),
    ]
