# Generated by Django 3.0.8 on 2020-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20201018_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat2',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
