# Generated by Django 3.0.8 on 2020-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20201025_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat1files',
            name='urlfield',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='cat2files',
            name='urlfield',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='fatfiles',
            name='urlfield',
            field=models.URLField(default='', null=True),
        ),
    ]
