# Generated by Django 3.0.8 on 2020-10-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20201025_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat1files',
            name='urlfield',
            field=models.URLField(blank=True, default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cat2files',
            name='urlfield',
            field=models.URLField(blank=True, default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fatfiles',
            name='urlfield',
            field=models.URLField(blank=True, default='', editable=False, null=True),
        ),
    ]
