# Generated by Django 3.0.8 on 2020-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20201025_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat1files',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='cat2files',
            name='urlfield',
        ),
        migrations.RemoveField(
            model_name='fatfiles',
            name='urlfield',
        ),
        migrations.AddField(
            model_name='cat1files',
            name='cat_1_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='cat2files',
            name='cat_2_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='fatfiles',
            name='fat_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
