# Generated by Django 3.0.8 on 2020-10-29 09:46

from django.db import migrations, models
import gdstorage.storage
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20201029_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='subject',
            name='syll_file',
            field=models.FileField(default='', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=resources.models.path_and_rename_syllabus),
        ),
    ]
